services:
    api:
        build: .
        image: fms-auth:${IMAGE_TAG}
        container_name: fms-api
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            DATABASE_NAME: ${DATABASE_NAME}