name: FMS CI/CD

on:
  push:
    branches:
      - project-setup

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: start application   
        run:  |
          docker compose up -d

      - name: Check container
        run: |
          sleep 5

          echo "-----Compose containers----"
          docker compose ps
          
          echo "----Docker Container----"
          docker ps

          echo "----application logs----"
          docker compose logs api

      - name: Check applications
        run : |
          curl -v http://localhost:8000

 

    