name: FMS CI/CD

on:
  push:
    branches:
      - project-setup

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run:  |
          docker build -t fms-auth:${{ github.sha }} .
          docker build -t fms-auth:latest .



      - name: Run Docker container
        run: |
          docker run -d \
            --name fms-auth-test \
            -p 8000:8000 \
            -e MONGODB_URL="${{ secrets.DATABASE_URL }}" \
            -e DATABASE_NAME = "${{ secrets.DATABASE_NAME }}" \
            fms-auth:${{ github.sha }}

      - name: Check container
        run: |
          sleep 5
          docker ps
          docker logs fms-auth-test
          if [ "$(docker inspect -f '{{.State.Running}}' fms-auth-test)" != "true" ]; then
            echo "Container failed to start"
            exit 1
          fi

      

 

    